"""Read geometry from images made by lpmake, not fixtures generated by the reader."""

from pathlib import Path
import random
import shutil
import subprocess
import sys
import tempfile
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from super_geometry import super_geometry


class SuperGeometry(unittest.TestCase):
    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.root = Path(tmp.name)
        self.tools = Path(shutil.which("lpmake")).resolve().parents[1]
        self.payload = self.root / "payload"
        self.payload.write_bytes(random.Random(0).randbytes(3 * 1024 * 1024))

    def make_image(self, name, size=32 * 1024 * 1024, *, sparse=True, compact=False, metadata_size=65536):
        directory = self.root / name
        directory.mkdir()
        image = directory / ("super_empty.img" if compact else "super.img")
        cmd = ["lpmake", "--metadata-size", str(metadata_size), "--metadata-slots", "3",
               "--super-name", "super", "--device", f"super:{size}", "--virtual-ab",
               "--partition", f"system_a:readonly:{self.payload.stat().st_size}:default", "--output", str(image)]
        if not compact:
            cmd += ["--image", f"system_a={self.payload}"]
        if sparse:
            cmd.append("--sparse")
        subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        return directory

    def test_raw_sparse_and_compact(self):
        expected = {"super_metadata_device": "super", "super_block_devices": "super",
                    "super_partition_size": 32 * 1024 * 1024, "super_super_device_size": 32 * 1024 * 1024}
        for name, options in [("raw", {"sparse": False}), ("sparse", {}), ("compact", {"compact": True})]:
            with self.subTest(name=name):
                self.assertEqual(super_geometry(self.tools, self.make_image(name, **options)), expected)

    def test_split_sparse(self):
        directory = self.make_image("source")
        expected = super_geometry(self.tools, directory)
        split = self.root / "split"
        split.mkdir()
        subprocess.run(["simg2simg", str(directory / "super.img"), str(split / "piece"), str(1024 * 1024)],
                       check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        for path in split.glob("piece.*"):
            path.rename(split / f"super_{int(path.suffix[1:]) + 1}.img")
        self.assertGreater(len(list(split.iterdir())), 1)
        self.assertEqual(super_geometry(self.tools, split), expected)

    def test_device_size_is_not_inherited(self):
        size = 64 * 1024 * 1024
        result = super_geometry(self.tools, self.make_image("larger", size))
        self.assertEqual(result["super_super_device_size"], size)
        self.assertEqual(result["super_partition_size"], size)

    def test_corrupt_missing_and_unsupported_geometry(self):
        for name, offset in [("geometry", 4096 + 8), ("header", 3 * 4096 + 12), ("table", 3 * 4096 + 256)]:
            directory = self.make_image(name, sparse=False)
            with (directory / "super.img").open("r+b") as f:
                f.seek(offset)
                value = f.read(1)
                f.seek(offset)
                f.write(bytes([value[0] ^ 1]))
            with self.subTest(name=name), self.assertRaises(ValueError):
                super_geometry(self.tools, directory)
        with self.assertRaises(ValueError):
            super_geometry(self.tools, self.make_image("unsupported", metadata_size=32768))
        with self.assertRaises(ValueError):
            super_geometry(self.tools, self.root / "missing")


if __name__ == "__main__":
    unittest.main()
